### ISSUE TITLE
Memory efficiency

### ISSUE THREAD

**Issue by ryanwebster90** [vlfeat/autonn#12] opened 2017-09-18 20:54 UTC
thanks Joao for this awesome repository :)

Autonn saves all variables in network evaluation, including those in layers which do not need the forward pass for derivative computation, like reshape, repmat, sum, etc. All layer derivatives are saved as well. So the convenience of not writing your derivatives by hand comes with a severe memory overhead. 

There isn't any mechanics in place for aggressive deletion of intermediate variables, like in MatConvNet's dagnn package (although there is optimizeVars for vl_nnrelu only). I've submitted a pull request for deletion of derivatives during the backward pass, which only requires a few lines of code.

To implement the full memory savings of MatConvNet, we could also delete variables on the forward pass. I've taken this approach:

(1) add precious property to Layer
(2) add varsFanOut to Net, set varsFanOut during compilation
(3) during eval, update a copy of varsFanOut, then delete varsFanOut == 0 i.e. vars which are no longer need
(4) set 'precious' to false for layers like transpose or non-differentiable layers. 

The code is here [precious-layers](https://github.com/ambient-space/autonn/tree/precious-layers) . It saves memory for functions which do not need the forward input at all. non-differentiable layers (numInputDer = 0) are made non-precious by default during compilation.

I've ran into the following issue: the commonly used functions repmat, mean, sum, reshape, permute, ipermute, do not need the input variables on the backward pass for computation, but need their size, and for this reason have to be precious. The solution requires modifying the arguments of the backward functions during forward evaluation, which is messy.

Any ideas? Is there a better approach?

**Comment by ambient-space** [comment] 2017-09-20 20:48
I've started coding mechanics for precious layers (see my [precious-layers](https://github.com/ambient-space/autonn/tree/precious-layers) branch), using the ideas in my previous comment. This code can be used to save memory for simple functions like transpose or relu (0 leak), which do not need the forward input at all. Additionally, non-differentiable layers (numInputDer = 0) are made non-precious by default. 

I've ran into the following issue: repmat, mean, sum, reshape, etc. do not need the input variables on the backward pass for computation, but need their size, and for this reason have to be precious. The solution to this seems to require modifying the arguments of the backward functions during forward evaluation, which is messy but could work.

On a similar note, evalOutputSize needs to run a dummy tensor through the network as autonn does not require functions to provide their output size (a good feature in my opinion). 

Any ideas?

**Comment by jotaf98** [comment] 2017-09-21 11:24
Hi! It's good to hear that, thanks for contributing back :)

This is tricky, but that just means it needs to be well thought out. You give some really good points to start with, and as you noticed there are different ways to attack this (sometimes complementary).

- I hadn't considered removing gradients as the backward pass proceeds (your pull request #11). That's an easy reduction of almost 1/2 of the memory! I'll make a couple of questions/suggestions there in the interest of performance (and my own understanding), but I think it's a great addition.

- The precious-layers contribution is also great, I think it can be made even faster though. The idea is to push the fanout logic to the compilation phase, and simply record in each layer which variables should be cleared after the forward call. This means that only one line of code (vars(layer.clearVars)=[]) needs to be added to the eval loop.

Essentially, adding code elsewhere can be done more recklessly but the eval loop has to be tight in order to keep the current strong performance. Can I just ask you to measure the training speed (on cifar and imagenet preferably) with/without the changes?

One more thing: Maybe the first option can be named conserveBackwardMemory and the second conserveForwardMemory? Or a single option to control both. Any suggestions?

**Comment by ryanwebster90** [comment] 2017-10-08 02:43
Hello again,
This post refers to the precious-layers pull request #13 , for memory savings during the forward pass. 

> The idea is to push the fanout logic to the compilation phase ... one line of code (vars(layer.clearVars)=[]) needs to be added to the eval loop.

Good suggestion! It's implemented now for forward and backward deletion.  

Common functions like reshape are not precious, but need the input tensor size on the backward pass. Instead of deleting variables on the forward pass, I replace them by their size. See line 138 of eval. During compilation, I replace non precious functions (e.g. reshape) by a version which expects a x_sz and not x. See nonprecious_der.m in the derivatives folder, implemented like autonn_der. The following functions are now made non-precious when you specify conserveMemory = true

reshape, circshift (newly overloaded), sum, permute, ipermute, squeeze, mean, flip, rot90, cat, vl_nnwsum

Subsref (and maybe a few others) are non precious but need special implementation.

> Can I just ask you to measure the training speed (on cifar and imagenet preferably) with/without the changes?

Here is my bench mark on a Quadro K2200 for the vgg 19 very deep network with input tensor sized
224x224x3x1

>VGG-19, 5000 forward/backward evaluations
(time (s))/numIter for vgg 19 conserveMemory = true:  3.226e-01
(time (s))/numIter for vgg 19 conserveMemory = false:  2.986e-01
net memory usage =  1.216e+09 bytes (conserveMemory = true)
net memory usage =  1.282e+09 bytes (conserveMemory = false)

I.e. ~ 0.02 seconds slower per forward/backward evaluation (~16 minutes slower for 100k evaluations). 
vgg-19 is not a network where you would consider conserveMemory though.

Here is a toy example that uses almost no memory when conserveMemory = true. 
You can see the network topology [here](https://imgur.com/alxHj24) which showcases most of the non precious functions implemented.

>net memory usage =  1.627e+04 bytes (conserveMemory = true)
net memory usage =  1.186e+07 bytes (conserveMemory = false)

*edited for brevity

**Comment by ryanwebster90** [comment] 2017-10-14 22:51
I'd like to continue a discussion on precious-layers #13 .

Many functions require a size on the backwards pass. That presents two problems: 

1. Avoiding repeated size calls during eval. Most of the time sizes never change anyways.
2. Derivative functions. Either they expect the data, a size, or there is behavior for both.

Ideas to improve (1) : 

- During only the first forward pass, whos(x) is called on every output variable and saved in net.forward.varsInfo. If any change in the info of the inputs is detected (a fast check outside the eval loop), varsInfo will be reset. 

Ideas to improve (2) : 

- There is only one version of the derivative, which expects a whos() struct by default. 

- There is only one version of the derivative, which checks isstruct() to set the size/type variables.

Any thoughts?

**Comment by jotaf98** [comment] 2017-10-15 23:02
Awesome!

That's very close to how I imagined it. It's possible to avoid some code duplication (for long-term maintainability) by having the original derivative implementations detect when the input is a size, instead of the separate nonprecious_der.m. I can think of a few ways to do this:

1) Explicitly: Use struct('size', sz) or {'size', sz} as the input. Pros: unambiguous. Cons: Verbose, maybe slightly slower.

2) Implicitly: Just pass in the size to *_der, and check with:
```
if isvector(x) && numel(x) ~= numel(dy)
  % it's size(x)
else
  % it's x
end
```
Pros: Fast, simple. Cons: Ambiguous for vector inputs.

3) Even more implicitly: Have an object DeletedTensor with a size property and that overloads size, ndims etc to return it. This way the existing *_der functions don't need modification. Pros: unambiguous, cool. Cons: Overloading in unexpected places makes things harder to debug, slowest.

Maybe 2) can be improved with some other checks. However, if x looks like a size vector the check will  fail.

I haven't had as much time as I'd like for this due to looming deadlines. If you can't do more edits I might just do them, however I'd like to hear your opinion on how this bit is handled!

There's always a speed hit when not reusing tensors, due to allocation or by preventing in-place operations. Maybe it should be possible to enable this non-precious functionality without necessarily wiping all the derivatives as the backward pass is done (i.e. have independent options for conservation strategies). I'll probably work on a more reusable benchmarking function to aid in these decisions.

**Comment by ryanwebster90** [comment] 2017-10-16 02:03
I don't like the isvector solution, lets scrap that. DeletedTensor is a creative idea (damn you and your overloading wizardry) and is pretty tempting. My only concern is this clause
```Matlab
isscalar(dy) && dy == 0  % special case, no derivative
    dx = zeros(size(x), 'like', x) ;
```
the 'like' x will present a problem, so some kind of code modification will have to happen regardless. Perhaps you could make a dummy variable method in DeletedTensor and do
```Matlab
isscalar(dy) && dy == 0  % special case, no derivative
    dx = zeros(size(x), 'like', x.dummyVar()) ;
```
which returns a type casted dummy variable. But this kind of nullifies using DeletedTensor in the first place. I think I like the explicit struct('size',sz) solution the most. I can write the code, I'm converting my current projects to autonn, which all run out of memory without precious-layers, so i'll get plenty use out of it. 

Two things to conclude this post:
(1) Can you explain the above code to me? I thought this was for default derivative behavior, but eval uses single(1) as a default derivative. Perhaps this is a seperate issue. 
(2) I'm accumulating somewhat of a "network zoo" for debugging. Debugging for "every possible topology" is an interesting new domain for me. Would you care to share privately with me a few of your networks (although I suspect your networks are more standard and you wouldn't use conserveMemory anyways). Also, do you have any tips for writing test suites? All my tests are semantic, just checking input/output is the same for conserveMemory = true/false and of course that is saved memory where it was supposed to.

**Comment by jotaf98** [comment] 2017-10-18 12:52
Haha thanks. Yeah better go with the safest option! I had a look at the updated code, it looks great and the functionality is all encapsulated nicely in struct_or_tensor_size.

1) Yes I also don't like the special case for scalars, but it exists to handle a special case.

Essentially, a scalar "0" is the initial derivative when starting backprop, because you can add any tensor shape or type to it, and it will conform. It is also faster than adding a tensor of zeros (i.e. A+0 is faster than A+zeros(size(A)) because the later needs to look up 2 arrays instead of 1).

Now, the problem is when you have non-differentiable layers in the mix. Some derivatives in the graph will end up being a scalar 0 if the layers that would contribute to them are non-differentiable, e.g. reshape(1:n, n, 1) (where n is a layer output; the colon operator is non-differentiable). The derivative of the colon operator is a scalar 0, and reshape can't handle it.

A better solution would be to remove such layers from the backpropagation order. This would take some static analysis of the graph, and it could be tricky. So I settled on this easier, temporary solution instead. I'd love to revisit it and do it better though.

2) I wouldn't mind sharing some, though all of my networks are not stand-alone image analysis CNNs; they need lots of extra bookkeeping to run. But you're right that there must be a standard way to test these things. Sam @albanie suggested that sampling a few popular nets from small to big might work: ResNet-50, AlexNet and one of the compact mobile networks would work. The idea would be to grab 3-4 pretrained nets from here:
https://github.com/vlfeat/matconvnet-contrib
http://www.vlfeat.org/matconvnet/pretrained/

And have a "benchmark" script that times them and shows a table, and allows overriding some options (like memory conservation, or choosing different models from a directory).

**Comment by jotaf98** [comment] 2017-10-22 22:31
Just an update, I added cnn_benchmark to make it easy to time any changes. At least on my laptop it seems to suggest that the current implementation of autonn is slightly slower than dagnn; this was not the case some months ago when I compared the two directly, but some change in the meanwhile must have changed things. I guess this shows that I should have standardized such benchmarks before, and some further optimization is in order ;)

**Comment by ryanwebster90** [comment] 2017-10-23 04:30
I mean memory efficiency is a hard decision you'll have to make for autonn. Do you want generality with a performance hit or do you just want speed (other example: complex number support for multiplicative layers)? Autonn's usefulness goes far beyond speed; it is in convenience, fast experimentation and code readability. In those regards it's far better than dagnn.

I'm curious about your sentiment on this. Do you see autonn as a general AD tool for all algorithms capable of backprop, or a tool for training convnets with a speed and convenience boost. If it's the latter, standard convnets (vgg, resnet, inception etc.) all use Conv, Relu, Bnorm as their core layers, which are all precious, so short circuiting is all you need. If you'd like, i'll share a few repositories with you which show how useful autonn can be outside of just convnets to try to convince you of the former.

**Comment by jotaf98** [comment] 2017-10-26 13:40
I agree with you that the main motivation is ease of prototyping exotic models! That's what got me started and what I mainly use it for.

I didn't mean that being a bit slower would disqualify a memory improvement -- it's extremely valuable and I'll include it in any case. The benchmarks were mainly out of curiosity, to quantify the tradeoff, and to allow discovering some low-hanging fruits in terms of speed optimization, if there are any.

I was surprised to see that the current evaluation loop has grown large enough that it's slower than dagnn. I really want to take a close look in a few weeks after the deadlines have passed, but of course this has no bearing on the memory optimizations at all.

**Comment by jotaf98** [comment] 2017-11-28 13:12
Finally had time to go through everything in detail and merge! Thanks again @ryanwebster90 for contributing this, it's such a great improvement. I'm closing the issue, but I think any follow-up discussions can still go here.

**Closed as completed by jotaf98** 2017-11-28 13:12 UTC
